default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_carousel_development

test:
  <<: *default
  database: product_carousel_test

production:
  <<: *default
  database: product_carousel_production
  username: product_carousel
  password: <%= ENV['SHOPIFY_TEST_DATABASE_PASSWORD'] %>
