# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69a9632666289388ece65277cbf7d14b2344b53f645ab0a9357d5026c3c55fae824504f35319f7cd10d5d2516a8852bb62c7194d8f7c628138b6710ca4336426

test:
  secret_key_base: 5fbdf90e082cf253cad7673b4b7d439d017539fe7ceec9e4337e7203a76a7a50091b91dc4bf70b3c42c79bbcb35d0eb2208479ff393ff8de474059191cc12c4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
